  version: '3.9'
  services:
    web:
      build: ./service
      container_name: django
      command: sh -c "python manage.py migrate && gunicorn service.wsgi:application --bind 0.0.0.0:8000"
      restart: on-failure
      environment:
        - DJANGO_SUPERUSER_USERNAME=admin
        - DJANGO_SUPERUSER_PASSWORD=123
        - DJANGO_SUPERUSER_EMAIL=admin@example.com
      volumes:
        - ./service/:/usr/src/service/
        - ./service/static/:/usr/src/service/static/
        - ./service/media/:/usr/src/service/media/
      expose:
        - 8000
      env_file:
        - .env.dev
      depends_on:
        - db

    db:
      image: postgres:14.6-alpine
      container_name: postgres_db
      restart: on-failure
      volumes:
        - ./postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=django_user
        - POSTGRES_PASSWORD=django_password
        - POSTGRES_DB=django_db
      ports:
        - 5432:5432

    nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 1337:80
      depends_on:
        - web
      volumes:
        - ./service/static/:/usr/src/service/static/
        - ./service/media/:/usr/src/service/media/

  volumes:
      postgres_data:
      static_volume:
      media_volume:





